# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: SNAPSHOT Build

on:
  push:
    branches: [ master ]

jobs:
  linux:
    if: "!contains(github.event.head_commit.message, 'cd skip')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup AdoptOpenJDK 16
        uses: joschi/setup-jdk@v2.3.0
        with:
          java-version: 16
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build JAR dist files
        run: ./gradlew dist
      - name: Build deb package
        env:
          WORKFLOW_RUN: ${{ github.run_number }}
        run: ./gradlew jpackage -PSNAPSHOT=true
      - name: Fix deb file names
        run: mv build/jpackage/*.deb Linux.HyperLap2D-SNAPSHOT.deb
      - name: Upload deb artifact
        uses: actions/upload-artifact@v2
        with:
          name: Linux.HyperLap2D-SNAPSHOT.deb
          path: Linux.HyperLap2D-SNAPSHOT.deb
      - name: Publish SNAPSHOT artifacts
        if: "!contains(github.event.head_commit.message, 'editor only')"
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: ./gradlew build publish -PSNAPSHOT=true

  windows:
    if: "!contains(github.event.head_commit.message, 'cd skip')"
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup AdoptOpenJDK 16
        uses: joschi/setup-jdk@v2.3.0
        with:
          java-version: 16
      - name: Build JAR dist files
        run: ./gradlew.bat dist
      - name: Build msi package
        env:
          WORKFLOW_RUN: ${{ github.run_number }}
        run: ./gradlew.bat jpackage -PSNAPSHOT=true
      - name: Fix file names
        run: mv build/jpackage/*.msi Windows.HyperLap2D-SNAPSHOT.msi
      - name: Upload msi artifact
        uses: actions/upload-artifact@v2
        with:
          name: Windows.HyperLap2D-SNAPSHOT.msi
          path: Windows.HyperLap2D-SNAPSHOT.msi

  macOS:
    if: "!contains(github.event.head_commit.message, 'cd skip')"
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup AdoptOpenJDK 16
        uses: joschi/setup-jdk@v2.3.0
        with:
          java-version: 16
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build JAR dist files
        run: ./gradlew dist
      - name: Build dmg package
        env:
          WORKFLOW_RUN: ${{ github.run_number }}
        run: ./gradlew jpackage -PSNAPSHOT=true
      - name: Fix file names
        run: mv build/jpackage/*.dmg macOS.HyperLap2D-SNAPSHOT.dmg
      - name: Upload dmg artifact
        uses: actions/upload-artifact@v2
        with:
          name: macOS.HyperLap2D-SNAPSHOT.dmg
          path: macOS.HyperLap2D-SNAPSHOT.dmg
